# Generated by Django 5.1.1 on 2026-04-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnoses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='cnn_confidence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='cnn_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='field_location',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='original_file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='rag_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='saved_by_user',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('validated', 'Validated'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=30),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='symptom_input',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='title',
            field=models.CharField(blank=True, default='', max_length=180),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='user_question',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='diagnosis',
            name='yolo_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
