# Generated by Django 5.1.1 on 2026-04-14 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(default='vegetable', max_length=80)),
                ('description', models.TextField(blank=True, default='')),
                ('default_planting_modes', models.JSONField(blank=True, default=list)),
                ('climate_profile', models.JSONField(blank=True, default=dict)),
                ('growth_profile', models.JSONField(blank=True, default=dict)),
                ('care_rules', models.JSONField(blank=True, default=dict)),
                ('is_beginner_friendly', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CropLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('address_text', models.CharField(blank=True, default='', max_length=255)),
                ('admin_area_1', models.CharField(blank=True, default='', max_length=120)),
                ('admin_area_2', models.CharField(blank=True, default='', max_length=120)),
                ('country_code', models.CharField(blank=True, default='VN', max_length=10)),
                ('timezone', models.CharField(default='Asia/Ho_Chi_Minh', max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_locations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CropPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('planting_mode', models.CharField(default='pot', max_length=30)),
                ('area_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('area_unit', models.CharField(default='m2', max_length=20)),
                ('plant_count', models.PositiveIntegerField(default=1)),
                ('planned_start_date', models.DateField()),
                ('recommended_start_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('needs_review', 'Needs review'), ('archived', 'Archived')], default='active', max_length=20)),
                ('suitability_score', models.PositiveIntegerField(default=0)),
                ('suitability_level', models.CharField(choices=[('suitable', 'Suitable'), ('borderline', 'Borderline'), ('not_recommended', 'Not recommended')], default='borderline', max_length=20)),
                ('summary', models.TextField(blank=True, default='')),
                ('ai_reasoning_summary', models.TextField(blank=True, default='')),
                ('plan_goal', models.CharField(blank=True, default='', max_length=40)),
                ('experience_level', models.CharField(blank=True, default='beginner', max_length=30)),
                ('plan_version', models.PositiveIntegerField(default=1)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_plans', to='crop_plans.crop')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='crop_plans', to='crop_plans.croplocation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CropPlanStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase_key', models.CharField(max_length=50)),
                ('step_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=180)),
                ('short_label', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('why_this_step_matters', models.TextField(blank=True, default='')),
                ('prerequisites', models.JSONField(blank=True, default=list)),
                ('tools_needed', models.JSONField(blank=True, default=list)),
                ('estimated_duration_minutes', models.PositiveIntegerField(default=0)),
                ('suggested_start_time', models.DateTimeField()),
                ('suggested_end_time', models.DateTimeField()),
                ('repeat_rule', models.JSONField(blank=True, null=True)),
                ('reminder_times', models.JSONField(blank=True, default=list)),
                ('completion_condition', models.TextField(blank=True, default='')),
                ('risk_notes', models.JSONField(blank=True, default=list)),
                ('weather_dependency', models.JSONField(blank=True, default=dict)),
                ('water_amount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('water_amount_unit', models.CharField(blank=True, default='', max_length=30)),
                ('fertilizer_amount_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fertilizer_amount_unit', models.CharField(blank=True, default='', max_length=30)),
                ('sunlight_requirement_text', models.CharField(blank=True, default='', max_length=150)),
                ('dependency_step_ids', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('current', 'Current'), ('completed', 'Completed'), ('skipped', 'Skipped'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('delay_reason', models.CharField(blank=True, default='', max_length=255)),
                ('sort_key', models.CharField(blank=True, default='', max_length=50)),
                ('user_notes', models.TextField(blank=True, default='')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='crop_plans.cropplan')),
                ('parent_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='crop_plans.cropplanstep')),
            ],
            options={
                'ordering': ['step_number', 'suggested_start_time'],
                'unique_together': {('crop_plan', 'step_number')},
            },
        ),
        migrations.CreateModel(
            name='CompletionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(default='completed', max_length=20)),
                ('note', models.TextField(blank=True, default='')),
                ('proof_image_url', models.URLField(blank=True, default='')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_logs', to=settings.AUTH_USER_MODEL)),
                ('crop_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_logs', to='crop_plans.cropplan')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_logs', to='crop_plans.cropplanstep')),
            ],
            options={
                'ordering': ['-logged_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('deep_link', models.CharField(blank=True, default='', max_length=255)),
                ('trigger_time', models.DateTimeField()),
                ('fallback_trigger_time', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(default='medium', max_length=20)),
                ('type', models.CharField(default='step_due', max_length=40)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('push', 'Push'), ('email', 'Email')], default='in_app', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='scheduled', max_length=20)),
                ('read', models.BooleanField(default=False)),
                ('completed_or_not', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('crop_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crop_plans.cropplan')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='crop_plans.cropplanstep')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['trigger_time'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=30)),
                ('event_time', models.DateTimeField(auto_now_add=True)),
                ('provider_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, default='')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crop_plans.reminder')),
            ],
            options={
                'ordering': ['-event_time'],
            },
        ),
        migrations.CreateModel(
            name='WeatherSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(default='nasa_power', max_length=50)),
                ('time_range_start', models.DateField()),
                ('time_range_end', models.DateField()),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('daily_series', models.JSONField(blank=True, default=list)),
                ('derived_metrics', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_snapshots', to='crop_plans.croplocation')),
            ],
            options={
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.AddField(
            model_name='cropplan',
            name='weather_snapshot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_plans', to='crop_plans.weathersnapshot'),
        ),
    ]
