# Generated by Django 5.1.1 on 2026-05-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_avatar_url_user_company_name_user_farm_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, default='Người dùng Leafiq', max_length=120),
        ),
    ]
